# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Scarlet Hammer Games
tagline:             'A student games group in the Ubisoft Game Lab competition.'
description:         'This is the blogitty.'
url:                 http://scarlethammergames.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Scarlet Hammer Games
  url:               scarlethammer.github.io
  email:             scarlethammergames@gmail.com

# Custom vars
version:             1.0.0
